# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/rose-pine.toml"]
[env]
TERM = "xterm-256color"

[font]
size = 22

[font.normal]
family = "UbuntuMono Nerd Font Mono"

[window]
decorations = "none"
startup_mode= "SimpleFullscreen"
blur = true
opacity = 0.95

[window.padding]
x = 7
y = 0

[keyboard]

bindings=[{ key= "Back", mods= "Control", chars= "\u0017" }]

[mouse]
bindings=[{ mouse= "Right", action= "Paste" }]
